


// Enumerated type that defines the list of tokens

enum Token {AT, COLOR, END,	HEIGHT, RECTANGLE, RIGHT_TRIANGLE, SCENE, WIDTH, COMMA, SEMICOLON, PERIOD, LEFT_PAREN,
    RIGHT_PAREN, IDENTIFIER, NUMBER, EOF, ISOSCELES, PARALLELOGRAM, REGULAR, TEXT}